'use strict'

/**
 * Signal engine state constants and helper Sets.
 * Shared between the state machine, scoring service, and socket adapter.
 */

const SIGNAL_STATES = Object.freeze({
  IDLE:                    'IDLE',
  OBSERVING:               'OBSERVING',
  LONG_BIAS:               'LONG_BIAS',
  SHORT_BIAS:              'SHORT_BIAS',
  LONG_SETUP:              'LONG_SETUP',
  SHORT_SETUP:             'SHORT_SETUP',
  LONG_ENTRY_SIGNAL:       'LONG_ENTRY_SIGNAL',
  SHORT_ENTRY_SIGNAL:      'SHORT_ENTRY_SIGNAL',
  LONG_POSITION_OPEN:      'LONG_POSITION_OPEN',
  SHORT_POSITION_OPEN:     'SHORT_POSITION_OPEN',
  LONG_EXIT_WARNING:       'LONG_EXIT_WARNING',
  SHORT_EXIT_WARNING:      'SHORT_EXIT_WARNING',
  LONG_EXIT_SIGNAL:        'LONG_EXIT_SIGNAL',
  SHORT_EXIT_SIGNAL:       'SHORT_EXIT_SIGNAL',
  COOLDOWN:                'COOLDOWN',
  INVALIDATED:             'INVALIDATED',
})

const POSITION_ACTIVE_STATES = new Set([
  SIGNAL_STATES.LONG_POSITION_OPEN,
  SIGNAL_STATES.SHORT_POSITION_OPEN,
  SIGNAL_STATES.LONG_EXIT_WARNING,
  SIGNAL_STATES.SHORT_EXIT_WARNING,
  SIGNAL_STATES.LONG_EXIT_SIGNAL,
  SIGNAL_STATES.SHORT_EXIT_SIGNAL,
])

const ENTRY_SIGNAL_STATES = new Set([
  SIGNAL_STATES.LONG_ENTRY_SIGNAL,
  SIGNAL_STATES.SHORT_ENTRY_SIGNAL,
])

const EXIT_SIGNAL_STATES = new Set([
  SIGNAL_STATES.LONG_EXIT_SIGNAL,
  SIGNAL_STATES.SHORT_EXIT_SIGNAL,
])

const EXIT_WARNING_STATES = new Set([
  SIGNAL_STATES.LONG_EXIT_WARNING,
  SIGNAL_STATES.SHORT_EXIT_WARNING,
])

const LONG_STATES = new Set([
  SIGNAL_STATES.LONG_BIAS,
  SIGNAL_STATES.LONG_SETUP,
  SIGNAL_STATES.LONG_ENTRY_SIGNAL,
  SIGNAL_STATES.LONG_POSITION_OPEN,
  SIGNAL_STATES.LONG_EXIT_WARNING,
  SIGNAL_STATES.LONG_EXIT_SIGNAL,
])

const SHORT_STATES = new Set([
  SIGNAL_STATES.SHORT_BIAS,
  SIGNAL_STATES.SHORT_SETUP,
  SIGNAL_STATES.SHORT_ENTRY_SIGNAL,
  SIGNAL_STATES.SHORT_POSITION_OPEN,
  SIGNAL_STATES.SHORT_EXIT_WARNING,
  SIGNAL_STATES.SHORT_EXIT_SIGNAL,
])

/** Minimum ms a signal stays active before it can expire. */
const ENTRY_SIGNAL_EXPIRY_MS = 30_000

/** Minimum ms an exit signal stays active before it can expire. */
const EXIT_SIGNAL_EXPIRY_MS  = 45_000

/** Cooldown duration after a closed/invalidated position. */
const COOLDOWN_DURATION_MS   = 60_000

module.exports = {
  SIGNAL_STATES,
  POSITION_ACTIVE_STATES,
  ENTRY_SIGNAL_STATES,
  EXIT_SIGNAL_STATES,
  EXIT_WARNING_STATES,
  LONG_STATES,
  SHORT_STATES,
  ENTRY_SIGNAL_EXPIRY_MS,
  EXIT_SIGNAL_EXPIRY_MS,
  COOLDOWN_DURATION_MS,
}
